### ISSUE TITLE
adding external libraries like antd and react-slider conflicts with loaders

### ISSUE THREAD

**Issue by kordeviant** [gilbarbara/react-redux-observables-boilerplate#1]
this is not an issue of your boilerplate but , other boilerplates work out of the box with inserting external modules but this one needs configuration . could you please help?

**Comment by gilbarbara** [comment]
@kordeviant can you show me some code? is it in a public repo?

**Comment by kordeviant** [comment]
[front-web.zip](https://github.com/gilbarbara/react-redux-observables-boilerplate/files/587682/front-web.zip)
i am sorry to upload it this way .. when i try to install [react-slick](https://github.com/akiran/react-slick) css do not get automaticalli imported and whe i try to manuall import scss in main scss , the relative imports inside scss located in node_modules cause errors in build. this problem comes also with ant.design the babel import line 

> ["import", [{ "libraryName": "antd", "style": true }]]: import js and css modularly (less source files)
causes error also. again this is not your problem and this issue should be closed , but i would really appreciate your help in this . great job anyway

**Comment by gilbarbara** [comment]
Hey,
Try adding the `.scss` suffix in your import? Since the directory has css, scss and less files the import might get confused.

I need to use slick-carousel in a project and I ended up creating a `_slick-carousel.scss` inside styles/vendor and loading it this way. I can't remember why exactly I did this way but it worked.
[_slick-carousel.scss.zip](https://github.com/gilbarbara/react-redux-observables-boilerplate/files/588135/_slick-carousel.scss.zip)

[s]

**Comment by gilbarbara** [comment]
@kordeviant Did it work? Let me know.

**Comment by kordeviant** [comment]
```
{
        test: /\.less$/,
        loader: [
          'style-loader',
          'css-loader?importLoaders=1',
          'less-loader',
        ],
      },
```
this loader made ant.design work with this babel plugin
```
"plugins": [
    ["import", [{ "libraryName": "antd" ,"style":true}]],
```
but i have still other problems that are probably due to my lack of knowledge..
the built src is so much heavy weight .. main js build is 824kb and map of it is 4mb

please if you had spare time take a look at it.
[front-web.zip](https://github.com/gilbarbara/react-redux-observables-boilerplate/files/594940/front-web.zip)

**Comment by gilbarbara** [comment]
Ok, I don't know this ant.design package but if you need `less` that's the way.

This build size is ok.. You could optimize your imports and/or remove packages that you don't use..
And you should serve these files with a gzip enabled web-server that will reduce the size drastically (2-3x).

The sourcemap isn't loaded for normal users, only if you viewing the source code in the inspector.
