### ISSUE TITLE
production issue

### ISSUE THREAD

**Issue by kordeviant** [gilbarbara/react-redux-observables-boilerplate#2]
no css file is being created when ''npm run build" only two assets files are moved to dist and jpg ones are not loaded. also when npm start, access from external ip's gets stuck in loader and some js resources are not available to download by their browsers.
[front-web 2.zip](https://github.com/gilbarbara/react-redux-observables-boilerplate/files/610686/front-web.2.zip)

**Comment by kordeviant** [comment]
upgrading to your latest commits and importing assets in js made them appear in dist and a css file was also created. but still access from external ip's gets stuck in loader. please if you have any suggestions on reducing the dist js file size please share, i have not added anything special but 728kb js is extremely large.

**Comment by gilbarbara** [comment]
Sorry, this is a simple boilerplate. Asset optimization is a whole different beast..
