### ISSUE TITLE
some prefixes get removed on production

### ISSUE THREAD

**Issue by kordeviant** [gilbarbara/react-redux-observables-boilerplate#3]
display: flex should compile to all prefixes like display: -webkit-flex. this happens in development but in production gets removed .

i have changed css loader in config.prod to "css?sourceMap&minimize&-autoprefixer" .. this fixed the issue

**Comment by gilbarbara** [comment]
Thanks.
Fixed in ee22664b6b8fbf0c7203830ae661b62a5bfa1aef
