### ISSUE TITLE
assert StatelessComponent

### ISSUE THREAD

**Issue by mcroba** [gilbarbara/react-redux-observables-boilerplate#4]
Hello,

first of all I would like to say thank you for this repo... it helps me a lot to put in place some part of my project.

It's not an issue but more a question about an assertion that I like in most of your test component.

```
it('should be a StatelessComponent', () => {
    expect(wrapper.instance().constructor.name).toBe('StatelessComponent');
});
```

Since React 16, `wrapper.instance()` return `null` for SFC so I'm wondering if you have an idea how we could still assert that?

Thanks in advance for your response

Sylvain

**Comment by gilbarbara** [comment]
Hello!

Thanks! 👍 
In the matter of fact, I'm updating this repo to use the latest dependencies so I'm about to work on this.

You could simply assert:
```js
it('should be a StatelessComponent', () => {
    expect(wrapper.instance()).toBeNull();
});
```

It's not my favorite assertion but get the job done.
If you ever find a more declarative way to identify SFCs, let me know.

**Comment by mcroba** [comment]
It's actually what I have done but I was not so happy with that neither :)

**Comment by gilbarbara** [comment]
It feels like`true === true`, right?

However the wrapper will throw if you try to mount/shallow an invalid input, so if there's no error and no instance it has to be an SFC.
