### ISSUE TITLE
Adding a dockerfile for development and production.

### ISSUE THREAD

**Issue by Yengas** [gilbarbara/react-redux-observables-boilerplate#6]
Any plans to add a sample development and production Dockerfile to this project? I could help with the process, in case you have some clue of what needs to be included in the image. As far as i tried, using `node:9.4.0-alpine` and installing `make, gcc, g++, python`(for node-gyp builds), `git` makes this run.

Could use multi-staged builds to copy over the downloaded/built dependencies into another `node:9.4.0-alpine` for prod. Inspecting similar boilerplates with Dockerfiles could help aswell.

I will make something that works for my small-sized project, sometime in the near future. Could open up a pull request for further development after that, if you want.

**Comment by gilbarbara** [comment]
Hey,

Not really. This is a simple boilerplate for a front-end PWA.
The whole CI/CD is not really part of this process and most users would use an external service through GitHub or already have a build pipeline in their company.

Thanks anyway!

**Comment by Yengas** [comment]
Been using this boilerplate for some small personal/school projects. I am putting the Dockerfile i use to deploy it on DO, hope it helps someone. Thanks for the boilerplate Gil!

**Dockerfile**
```Dockerfile
FROM node:8.9.4-stretch as dependencies
# Set the workdir, and move package.json only
WORKDIR /application
ADD ./package*.json ./

# Install all node modules
RUN npm install

FROM node:8.9.4-stretch as builder

RUN npm install -g webpack-cli

# Set the workdir, and move all files.
WORKDIR /application
ADD . .

# Remove and copy node_modules for the target system
RUN rm -rf /application/node_modules
COPY --from=dependencies /application/node_modules /application/node_modules

# build the project into the dist folder.
RUN npm run build

FROM nginx:1.13.10 as release

COPY --from=builder /application/dist /usr/share/nginx/html
# Add google website admin related files to the website homepage.
ADD ./assets/google*.html /usr/share/nginx/html/
# Add sitemap to the website root folder.
ADD ./assets/sitemap.xml /usr/share/nginx/html/

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
```

**docker-compose.yml**
```yaml
version: '3'
services:
  application:
    build: .
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
```

**nginx.conf**
```conf
server {
    listen       80;
    server_name  yourwebsite.com;
    root   /usr/share/nginx/html/;
    index index.html;

    location / {
        try_files $uri /index.html;
    }
}
```
